export type MinecraftDeathReason =
  | 'death.fell.accident.generic'
  | 'death.attack.player'
  | 'death.fell.assist'
  | 'death.attack.mob'
  | 'death.attack.lava'
  | 'death.attack.arrow'
  | 'death.attack.outOfWorld'
  | 'death.attack.cactus'
  | 'death.attack.drown'
  | 'death.attack.flyIntoWall'
  | 'death.fell.killer'
  | 'death.attack.explosion.player'
  | 'death.attack.inWall'
  | 'death.attack.inFire'
